<?php

namespace AppBundle\Repository;

/**
 * PromotionCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionCoursRepository extends \Doctrine\ORM\EntityRepository 
{

}
