easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

jess_scola:
    resource: "@JessScolaBundle/Controller/"
    prefix:   /scola

restAPI:
    type: rest
    resource: Jess\scolaBundle\Controller\RestController
    prefix : /api

custom_rest_route:
    path: /custom/index
    defaults : {_controller:JessScolaBundle:Rest:index}

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#login_check:
#    path:   /login_check

#logout:
#    path:   /logout





