# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
     #avatar_directory : "%kernel.root_dir%/../web/uploads/avatar"

#services:
#    adder:
#        class: jess\tutoBundle\EventListener\MyListener
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
#    adder:a
#       class: jess\tutoBundle\EventListener\MyListener
#       arguments: ["Message"]
#       tags:
#            - { name: doctrine.event_listener, event: postPersist }

#    uploader:
#          class: jess\tutoBundle\Service\UploadService
#           arguments: [%avatars_directory%]

#    upload_listener:
#            class: jess\tutoBundle\EventListener\UploadListener
#            arguments: ['@uploader']
#            tags:
#                - { name: doctrine.event_listener, event: prePersist }
#                - { name: doctrine.event_listener, event: preUpdate }
#                - { name: doctrine.event_listener, event: onFlush }
#    my.subscriber:
#            class: jess\tutoBundle\EventListener\Suscriber#
 #           tags:
 #               - { name: doctrine.event_subscriber, connection: default }




